import { useCallback, useState } from "react";
import Head from "next/head";

import Top from "~/components/Top";
import Categories from "~/pages/projects/categories";
import ProjectList from "~/pages/projects/list";
import Tags from "~/pages/projects/tags";

export default function ProjectPage() {
  const [filterVisible, setFilterVisible] = useState(true);

  const onChangeFilterVisible = useCallback(() => {
    setFilterVisible((prev) => !prev);
  }, []);

  return (
    <>
      <Head>
        <title>ESNext - Projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto flex w-full max-w-screen-2xl flex-col px-5 md:px-10 lg:px-16">
        <Tags
          onChangeFilter={onChangeFilterVisible}
          categoryVisible={filterVisible}
        />
        <div className="flex">
          <Categories visible={filterVisible} />
          <ProjectList />
        </div>
      </div>
      <Top />
      {/* <main className="bg-primary-color flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main> */}
    </>
  );
}
