export const category = [
  {
    id: 1,
    name: 'FrontEnd Development',
    slug: 'frontend',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 2,
    name: 'BackEnd Development',
    slug: 'backend',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 3,
    name: 'State Management',
    slug: 'state-management',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 4,
    name: 'Testing',
    slug: 'testing',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 5,
    name: 'Mobile Development',
    slug: 'mobile',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 6,
    name: 'Static Site Generators',
    slug: 'static-site-generators',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 7,
    name: 'Build Tools',
    slug: 'build-tools',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 8,
    name: 'Style & CSS',
    slug: 'style-css',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 9,
    name: 'Desktop Development',
    slug: 'desktop',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 10,
    name: 'Data Visualization',
    slug: 'data-visualization',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 11,
    name: 'Utilities',
    slug: 'utilities',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 12,
    name: 'Security & Authentication',
    slug: 'security-authentication',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 13,
    name: 'Server-Side Rendering & Optimization',
    slug: 'server-side-rendering-optimization',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 14,
    name: 'Cloud & DevOps',
    slug: 'cloud-devops',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
  {
    id: 15,
    name: 'Internationalization & Localization',
    slug: 'internationalization-localization',
    icon: 'logos:javascript',
    bg_color: '#0277BD30',
  },
];
