export const category = [
  {
    name: "ALL",
    icon: "fxemoji:fire",
    count: 1123,
    color: "##FF8F1F30",
  },
  {
    name: "Most Popular",
    icon: "fxemoji:fire",
    count: 13,
    color: "##FF8F1F30",
  },
  {
    name: "FrontEnd Frameworks",
    icon: "logos:javascript",
    count: 116,
    color: "#F7DF1C30",
  },
  {
    name: "React EcoSystem",
    icon: "logos:react",
    count: 13,
    color: "#00D9FE30",
  },
  {
    name: "Vue EcoSystem",
    icon: "logos:vue",
    count: 63,
    color: "#40B98330",
  },
  {
    name: "BackEnd Frameworks",
    icon: "logos:nodejs-icon",
    count: 46,
    color: "#539F4330",
  },
  {
    name: "Build Tools",
    icon: "logos:webpack",
    count: 46,
    color: "##8ED6FB30",
  },
  {
    name: "Mobile Frameworks",
    icon: "logos:typescript-icon",
    count: 46,
    color: "#3178C630",
  },
  {
    name: "CSS",
    icon: "skill-icons:css",
    count: 16,
    color: "#0277BD30",
  },
  {
    name: "Testing",
    icon: "logos:jest",
    count: 116,
    color: "#99425B30",
  },
  {
    name: "Desktop Frameworks",
    icon: "logos:electron",
    count: 116,
    color: "#48838F30",
  },
  {
    name: "Static Site Generators",
    icon: "logos:docusaurus",
    count: 116,
    color: "#3ECC6030",
  },
  {
    name: "State Management",
    icon: "logos:redux",
    count: 116,
    color: "#774ABC30",
  },
  {
    name: "GraphQL",
    icon: "logos:graphql",
    count: 116,
    color: "#E535AB30",
  },
];
